spring:
  application:
    name: springbootapplication

  profiles:
    active: online

  datasource:
    url: jdbc:mysql://localhost:3306/testing_schema
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    user:
      name: sai
      password: Sai@123
      roles: ADMIN,USER

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

server:
  port: 9090
  servlet:
    context-path: /sba

logging:
  file:
    name: /app/logs/app.log   # <-- logs will also go here
  level:
    root: INFO
    org.springdoc: DEBUG
    org.springframework.web: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
