apiVersion: v1
kind: Service
metadata:
  name: employee-app
  labels:
    app: employee-app
spec:
  type: NodePort
  selector:
    app: employee-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
